local test = require "core.test"
local H = dofile("tests/helper.inc")
local mp = H.mp

local function roundtrip(v)
  local packed = mp.pack(v)
  local unpacked, _ = mp.unpack(packed)
  test.same(unpacked, v)
  return packed, unpacked
end

local function byte_str(s)
  return s:gsub(".", function(c) return string.format("0x%02x ", c:byte()) end)
end

local function packed_bytes(v)
  local p = mp.pack(v)
  return byte_str(p)
end

test.describe("messagepack", function()
  test.describe("nil and booleans", function()
    test.it("packs nil as 0xc0", function()
      test.equal(packed_bytes(nil), "0xc0 ")
      test.equal(mp.unpack(mp.pack(nil)), nil)
    end)
    test.it("packs false as 0xc2 and true as 0xc3", function()
      test.equal(packed_bytes(false), "0xc2 ")
      test.equal(packed_bytes(true), "0xc3 ")
      test.equal(mp.unpack(mp.pack(false)), false)
      test.equal(mp.unpack(mp.pack(true)), true)
    end)
  end)

  test.describe("unsigned integers", function()
    test.it("uses positive fixint for 0..127", function()
      test.equal(packed_bytes(0), "0x00 ")
      test.equal(packed_bytes(127), "0x7f ")
    end)
    test.it("uses uint8 (0xcc) for 128..255", function()
      test.equal(packed_bytes(128), "0xcc 0x80 ")
      test.equal(packed_bytes(255), "0xcc 0xff ")
    end)
    test.it("uses uint16 (0xcd) for 256..65535", function()
      test.equal(packed_bytes(256), "0xcd 0x01 0x00 ")
      test.equal(packed_bytes(65535), "0xcd 0xff 0xff ")
    end)
    test.it("uses uint32 (0xce) above 65535", function()
      test.equal(packed_bytes(65536), "0xce 0x00 0x01 0x00 0x00 ")
      test.equal(packed_bytes(4294967295), "0xce 0xff 0xff 0xff 0xff ")
    end)
    test.it("roundtrips unsigned values across boundaries", function()
      for _, n in ipairs({0, 1, 127, 128, 255, 256, 65535, 65536, 4294967295}) do
        roundtrip(n)
      end
    end)
  end)

  test.describe("negative integers", function()
    test.it("uses negative fixint for -1..-32", function()
      test.equal(packed_bytes(-1), "0xff ")
      test.equal(packed_bytes(-32), "0xe0 ")
    end)
    test.it("uses int8 (0xd0) for -33..-128", function()
      test.equal(packed_bytes(-33), "0xd0 0xdf ")
      test.equal(packed_bytes(-128), "0xd0 0x80 ")
    end)
    test.it("uses int16 (0xd1) for -129..-32768", function()
      test.equal(packed_bytes(-129), "0xd1 0xff 0x7f ")
      test.equal(packed_bytes(-32768), "0xd1 0x80 0x00 ")
    end)
    test.it("uses int32 (0xd2) below -32768", function()
      local p = mp.pack(-32769)
      test.equal(p:byte(1, 1), 0xd2)
      test.equal(string.unpack(">i4", p:sub(2, 5)), -32769)
      test.equal(p:byte(1, 1), 0xd2)
      local p2 = mp.pack(-2147483648)
      test.equal(string.unpack(">i4", p2:sub(2, 5)), -2147483648)
    end)
    test.it("roundtrips negative values across boundaries", function()
      for _, n in ipairs({-1, -32, -33, -128, -129, -32768, -32769, -2147483648}) do
        roundtrip(n)
      end
    end)
  end)

  test.describe("floats", function()
    test.it("packs non-integer numbers as float64 (0xcb)", function()
      local p = mp.pack(3.14)
      test.equal(p:byte(1, 1), 0xcb)
      test.equal(#p, 9)
    end)
    test.it("roundtrips floats", function()
      roundtrip(3.14)
      roundtrip(-0.5)
      roundtrip(123456.789)
      roundtrip(1.5)
    end)
    test.it("packs whole-valued floats as integers", function()
      local p = mp.pack(2.0)
      test.equal(p:byte(1, 1), 0x02)
      test.equal(mp.unpack(p), 2)
    end)
    test.it("unpacks 4-byte float (0xca) format", function()
      local packed = string.pack(">Bf", 0xca, 1.5)
      test.near(mp.unpack(packed), 1.5, 1e-6)
    end)
  end)

  test.describe("strings", function()
    test.it("uses fixstr (0xa0..0xbf) for 0..31 bytes", function()
      test.equal(packed_bytes(""), "0xa0 ")
      test.equal(string.byte(mp.pack(("a"):rep(31))), 0xa0 + 31)
    end)
    test.it("uses str8 (0xd9) for 32..255 bytes", function()
      local p = mp.pack(("a"):rep(32))
      test.equal(p:byte(1, 1), 0xd9)
      test.equal(p:byte(2, 2), 32)
      test.equal(#mp.pack(("a"):rep(255)), 1 + 1 + 255)
    end)
    test.it("uses str16 (0xda) for 256..65535 bytes", function()
      local p = mp.pack(("a"):rep(256))
      test.equal(p:byte(1, 1), 0xda)
      test.equal(string.unpack(">I2", p:sub(2, 3)), 256)
    end)
    test.it("uses str32 (0xdb) above 65535 bytes", function()
      local p = mp.pack(("a"):rep(65536))
      test.equal(p:byte(1, 1), 0xdb)
      test.equal(string.unpack(">I4", p:sub(2, 5)), 65536)
    end)
    test.it("roundtrips strings across boundaries", function()
      for _, n in ipairs({0, 1, 31, 32, 255, 256, 65535, 65536}) do
        roundtrip(("x"):rep(n))
      end
    end)
    test.it("roundtrips unicode bytes", function()
      roundtrip("héllo wörld")
      roundtrip("日本語")
    end)
  end)

  test.describe("arrays", function()
    test.it("uses fixarray (0x90..0x9f) for 0..15 items", function()
      test.equal(packed_bytes({}), "0x90 ")
      test.equal(string.byte(mp.pack({1, 2, 3})), 0x90 + 3)
    end)
    test.it("uses array16 (0xdc) for 16..65535 items", function()
      local big = {}
      for i = 1, 16 do big[i] = i end
      local p = mp.pack(big)
      test.equal(p:byte(1, 1), 0xdc)
      test.equal(string.unpack(">I2", p:sub(2, 3)), 16)
    end)
    test.it("uses array32 (0xdd) above 65535 items", function()
      local big = {}
      for i = 1, 65536 do big[i] = 1 end
      local p = mp.pack(big)
      test.equal(p:byte(1, 1), 0xdd)
      test.equal(string.unpack(">I4", p:sub(2, 5)), 65536)
    end)
    test.it("roundtrips arrays of mixed types", function()
      roundtrip({1, "two", true, {nested = "ok"}})
      roundtrip({{1, 2}, {3, 4}, {"deep", {{"er"}}}})
    end)
    test.it("treats sparse/holes tables as maps", function()
      -- {1, nil, 3} has a hole; is_array returns false -> packed as map
      local p = mp.pack({1, nil, 3})
      test.equal(p:byte(1, 1) >= 0x80 and p:byte(1, 1) <= 0x8f, true)
    end)
  end)

  test.describe("maps", function()
    test.it("uses fixmap (0x80..0x8f) for 0..15 pairs", function()
      local p = mp.pack({a = 1})
      test.equal(p:byte(1, 1), 0x81)
    end)
    test.it("uses map16 (0xde) for 16..65535 pairs", function()
      local m = {}
      for i = 1, 16 do m["k" .. i] = i end
      local p = mp.pack(m)
      test.equal(p:byte(1, 1), 0xde)
      test.equal(string.unpack(">I2", p:sub(2, 3)), 16)
    end)
    test.it("uses map32 (0xdf) above 65535 pairs", function()
      local m = {}
      for i = 1, 65536 do m["k" .. i] = 1 end
      local p = mp.pack(m)
      test.equal(p:byte(1, 1), 0xdf)
      test.equal(string.unpack(">I4", p:sub(2, 5)), 65536)
    end)
    test.it("packs map keys as strings", function()
      -- {key="v"}: non-sequential keys -> map; key packed as fixstr "key"
      local p = mp.pack({key = "v"})
      test.equal(p:byte(1, 1), 0x81)
      test.equal(p:byte(2, 2), 0xa3) -- fixstr length 3
      test.equal(p:sub(3, 5), "key")
      test.same(mp.unpack(p), {key = "v"})
    end)
    test.it("roundtrips maps with string keys", function()
      roundtrip({name = "x", nested = {deep = {value = 42}}})
    end)
  end)

  test.describe("concatenated stream with offset advancing", function()
    test.it("unpacks multiple packed values back to back", function()
      local stream = mp.pack(1)
        .. mp.pack("hello")
        .. mp.pack({10, 20})
        .. mp.pack(true)
        .. mp.pack(nil)
      local offset = 1
      local v1, o1 = mp.unpack(stream, offset)
      local v2, o2 = mp.unpack(stream, o1)
      local v3, o3 = mp.unpack(stream, o2)
      local v4, o4 = mp.unpack(stream, o3)
      local v5 = mp.unpack(stream, o4)
      test.equal(v1, 1)
      test.equal(v2, "hello")
      test.same(v3, {10, 20})
      test.equal(v4, true)
      test.is_nil(v5)
    end)
  end)

  test.describe("error handling", function()
    test.it("errors when packing an unsupported type", function()
      test.error(function() mp.pack(function() end) end, "unsupported")
      test.error(function() mp.pack(coroutine.create(function() end)) end, "unsupported")
    end)
    test.it("errors when unpacking an unknown byte", function()
      test.error(function() mp.unpack(string.char(0xc1)) end, "unsupported binary")
    end)
    test.it("returns nil past end of string", function()
      test.is_nil(mp.unpack("", 1))
      test.is_nil(mp.unpack("", 5))
    end)
  end)

  test.describe("nil placeholder in array roundtrip", function()
    test.it("converts holed tables into string-keyed maps", function()
      -- {1, nil, 2} has a hole; is_array returns false so it is packed as a
      -- map whose keys are the stringified numeric indices.
      local packed = mp.pack({1, nil, 2})
      local unpacked = mp.unpack(packed)
      test.equal(type(unpacked), "table")
      test.equal(unpacked["1"], 1)
      test.equal(unpacked["3"], 2)
      test.is_nil(unpacked[1])
      test.is_nil(unpacked[2])
      test.is_nil(unpacked[3])
    end)
  end)
end)
